basic/urls.py
from django.conf.urls import url
from basic import views
app_name = 'basic'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.user_login, name='user_login'),
]

users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic import views
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^basic/', include('basic.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'ˆlogout/$', views.user_logout, name='user_logout'),
    url(r'^special/$', views.special, name='special'),
]

basic/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

basic/forms.py
from django import forms
from django.contrib.auth.models import User
from basic.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

basic/views.py
from django.shortcuts import render
from basic.forms import UserForm, UserProfileInfoForm

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
# Create your views here.
def index(request):
    return render(request, "basic/index.html")

def register(request):
    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    context = { 'user_form': user_form, 'profile_form': profile_form, 'registered': registered }
    return render(request, "basic/registration.html", context)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not active')
        else:
            print('Someone tried to login and failed')
            print('Username: {} and password {}'.format(username, password))
            return HttpResponse('invalid login details supplied')
    else:
        return render(request, 'basic/login.html')

@login_required
def special(request):
    return HttpResponse('You are logged in')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/basic/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic:register' %}">Register</a>
            </li>
            <li class="nav-item">
            {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
            {% else %}
              <a class="nav-link" href="{% url 'basic:user_login' %}">Login</a>
            {% endif %}
            </li>
          </ul>
        </div>
      </nav>
      <div class="container">
        {% block body_block %}
        {% endblock %}
      </div>
    </div>
  </body>
</html>

templates/basic/index.html
{% extends 'basic/base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Django level five</h1>
  </div>
{% endblock %}

templates/basic/login.html
{% extends 'basic/base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please login</h1>
    <form action="{% url 'basic:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter username">
      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">
    </form>
  </div>
{% endblock %}

templates/basic/registration.html
{% extends 'basic/base.html' %}
{% load staticfiles %}

{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering</h1>
    {% else %}
      <h1>Register here</h1>
      <h3>Fill out the form</h3>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" value="Register">
      </form>
    {% endif %}
  </div>
{% endblock %}